name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - complete

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull exalted100/cloud-computing-practise:latest
    - name: Delete old docker container
      run: sudo docker rm -f cloud-computing-practise-container || true
    - name: Run Docker COntainer
      run: sudo docker run -d -p 8080:8080 --name cloud-computing-practise-container exalted100/cloud-computing-practise:latest
